networks:
  kong-net:
    driver: bridge

services:
  consul-server:
    image: consul:1.15.4
    networks:
      - kong-net
    ports:
      - "8500:8500" # Consul HTTP API
      - "8600:8600/udp" # Consul DNS
    environment:
      CONSUL_BIND_INTERFACE: eth0
      CONSUL_CLIENT_INTERFACE: eth0
      CONSUL_LOCAL_CONFIG: |
        {
          "datacenter": "dc1",
          "server": true,
          "bootstrap_expect": 1,
          "ui": true
        }
    command:
      [
        "agent",
        "-server",
        "-bind=0.0.0.0",
        "-client=0.0.0.0",
        "-ui",
        "-datacenter=dc1",
      ]

  kong-database:
    image: postgres:13
    networks:
      - kong-net
    ports:
      - "6001:5432"
    environment:
      POSTGRES_USER: ${KONG_PG_USER}
      POSTGRES_DB: ${KONG_PG_DB_NAME}
      POSTGRES_PASSWORD: ${KONG_POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${KONG_PG_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  kong-gateway-database-migration:
    build:
      context: .
      dockerfile: Dockerfile.kong-gateway
    networks:
      - kong-net
    environment:
      KONG_DATABASE: ${KONG_DATABASE}
      KONG_PG_HOST: ${KONG_PG_HOST}
      KONG_PG_USER: ${KONG_PG_USER}
      KONG_PG_PASSWORD: ${KONG_POSTGRES_PASSWORD}
    depends_on:
      kong-database:
        condition: service_healthy
    restart: "no"
    command: ["sh", "-c", "kong migrations bootstrap"]

  kong-gateway:
    build:
      context: .
      dockerfile: Dockerfile.kong-gateway
    networks:
      - kong-net
    environment:
      KONG_DATABASE: ${KONG_DATABASE}
      KONG_PG_HOST: ${KONG_PG_HOST}
      KONG_PG_USER: ${KONG_PG_USER}
      KONG_PG_PASSWORD: ${KONG_POSTGRES_PASSWORD}
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"
    restart: always
    depends_on:
      kong-database:
        condition: service_healthy
      kong-gateway-database-migration:
        condition: service_completed_successfully
    command: ["kong", "docker-start"]
    healthcheck:
      test: ["CMD-SHELL", "kong health"]
      interval: 10s
      timeout: 10s
      retries: 10

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile.applications
      args:
        APP: auth
        PORT: 3000
    networks:
      - kong-net
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - consul-server
    volumes:
      - ./consul-config:/consul/config
      - consul-auth-data:/consul/data # Volume for Consul data directory

volumes:
  consul-auth-data:
